<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EduPlatform.Infrastructure</RootNamespace>
    <AssemblyName>EduPlatform.Infrastructure</AssemblyName>
    <!-- System.Security.Cryptography.Xml flagged via transitive deps (Npgsql).
         Nie używamy XML signatures w aplikacji — ryzyko nieaplikowalne. -->
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduPlatform.Domain\EduPlatform.Domain.csproj" />
  </ItemGroup>

</Project>
